apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: hello-deployment
spec:
  selector:
    matchLabels:
      app: hello-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-deployment
    spec:
      containers:
      - name: hello-deployment
        image: katochm/firstrepo:latest
        ports:
        - containerPort: 8081
        command: ['sh', '-c', "java -jar /app.jar"]
 #     containers:
  #    - name: katacoda
   #     image: docker-http-server:latest
    #    ports:
     #   - containerPort: 80
